"""add predict

Revision ID: 00a7b774fe59
Revises: 3be13f1bb991
Create Date: 2026-01-13 20:51:28.355827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a7b774fe59'
down_revision: Union[str, Sequence[str], None] = '3be13f1bb991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('gap_rate', sa.Float(), nullable=False),
    sa.Column('stock_open', sa.Float(), nullable=False),
    sa.Column('prob_up', sa.Float(), nullable=False),
    sa.Column('prob_down', sa.Float(), nullable=False),
    sa.Column('predicted_direction', sa.Integer(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('return_if_up', sa.Float(), nullable=False),
    sa.Column('return_if_down', sa.Float(), nullable=False),
    sa.Column('max_return_if_up', sa.Float(), nullable=True),
    sa.Column('take_profit_target', sa.Float(), nullable=True),
    sa.Column('signal', sa.Enum('BUY', 'HOLD', 'SELL', name='signaltype'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=True),
    sa.Column('actual_close', sa.Float(), nullable=True),
    sa.Column('actual_high', sa.Float(), nullable=True),
    sa.Column('actual_low', sa.Float(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('return_diff', sa.Float(), nullable=True),
    sa.Column('actual_max_return', sa.Float(), nullable=True),
    sa.Column('max_return_diff', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'prediction_date', name='uq_gap_predictions_stock_date')
    )
    op.create_index('idx_gap_predictions_date', 'gap_predictions', ['prediction_date'], unique=False)
    op.create_index('idx_gap_predictions_signal', 'gap_predictions', ['signal'], unique=False)
    op.create_index('idx_gap_predictions_stock_code', 'gap_predictions', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gap_predictions_stock_code', table_name='gap_predictions')
    op.drop_index('idx_gap_predictions_signal', table_name='gap_predictions')
    op.drop_index('idx_gap_predictions_date', table_name='gap_predictions')
    op.drop_table('gap_predictions')
    # ### end Alembic commands ###
