"""fix strategy_table_add_weight4

Revision ID: 01706b4ad2b4
Revises: 29a8fc5377da
Create Date: 2026-01-17 00:29:29.195680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01706b4ad2b4'
down_revision: Union[str, Sequence[str], None] = '29a8fc5377da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_strategy_stock', sa.Column('target_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_strategy_stock', 'target_quantity')
    # ### end Alembic commands ###
