"""fix strategy_table_add_weight

Revision ID: 22486c0131ef
Revises: c2e402d38147
Create Date: 2026-01-16 18:30:52.071028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22486c0131ef'
down_revision: Union[str, Sequence[str], None] = 'c2e402d38147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_weight',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('weight_type', sa.Enum('EQUAL', 'MARKETCAP', 'VOLUME', 'PRICE', name='weighttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_strategy', sa.Column('weight_type', sa.Enum('EQUAL', 'MARKETCAP', 'VOLUME', 'PRICE', name='weighttype'), nullable=True))
    op.add_column('user_strategy', sa.Column('weight_type_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_strategy', 'strategy_weight', ['weight_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_strategy', type_='foreignkey')
    op.drop_column('user_strategy', 'weight_type_id')
    op.drop_column('user_strategy', 'weight_type')
    op.drop_table('strategy_weight')
    # ### end Alembic commands ###
