"""add stocks

Revision ID: 28a5368de9dc
Revises: 9efb1cd96204
Create Date: 2026-01-12 10:12:14.718588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a5368de9dc'
down_revision: Union[str, Sequence[str], None] = '9efb1cd96204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kospi_open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kospi_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kospi_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kospi_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kospi_volume', sa.BigInteger(), nullable=True),
    sa.Column('kospi_gap_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('kosdaq_open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kosdaq_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kosdaq_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kosdaq_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kosdaq_volume', sa.BigInteger(), nullable=True),
    sa.Column('kosdaq_gap_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('kospi200_open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kospi200_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kospi200_gap_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index('idx_market_indices_date', 'market_indices', ['date'], unique=False)
    op.create_table('stock_metadata',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.Enum('KOSPI', 'KOSDAQ', name='exchange'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELISTED', 'SUSPENDED', name='stockstatus'), nullable=False),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gap_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prev_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prev_range_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prev_upper_shadow', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('prev_lower_shadow', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('atr_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bollinger_position', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('bollinger_upper', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bollinger_middle', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bollinger_lower', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ma_5', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ma_20', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ma_50', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('above_ma5', sa.Integer(), nullable=True),
    sa.Column('above_ma20', sa.Integer(), nullable=True),
    sa.Column('above_ma50', sa.Integer(), nullable=True),
    sa.Column('ma5_ma20_cross', sa.Integer(), nullable=True),
    sa.Column('return_5d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('return_20d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('consecutive_up_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_stock_prices_symbol_date')
    )
    op.create_index('idx_stock_prices_date', 'stock_prices', ['date'], unique=False)
    op.create_index('idx_stock_prices_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_prices_symbol_date', table_name='stock_prices')
    op.drop_index('idx_stock_prices_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('stock_metadata')
    op.drop_index('idx_market_indices_date', table_name='market_indices')
    op.drop_table('market_indices')
    # ### end Alembic commands ###
