"""fix strategy_table_add_weight3

Revision ID: 29a8fc5377da
Revises: d599c7d66b9b
Create Date: 2026-01-16 23:40:21.866225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a8fc5377da'
down_revision: Union[str, Sequence[str], None] = 'd599c7d66b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_strategy', sa.Column('investment_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategy', 'investment_weight')
    # ### end Alembic commands ###
