"""add target_sell

Revision ID: 2c4c6175cd87
Revises: c661ec196c07
Create Date: 2026-01-21 10:51:00.906032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4c6175cd87'
down_revision: Union[str, Sequence[str], None] = 'c661ec196c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_strategy_stock', sa.Column('target_sell_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_strategy_stock', 'target_sell_price')
    # ### end Alembic commands ###
