"""init

Revision ID: 3be13f1bb991
Revises: 
Create Date: 2026-01-13 16:11:29.852524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be13f1bb991'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kospi_open', sa.Float(), nullable=True),
    sa.Column('kospi_high', sa.Float(), nullable=True),
    sa.Column('kospi_low', sa.Float(), nullable=True),
    sa.Column('kospi_close', sa.Float(), nullable=True),
    sa.Column('kospi_volume', sa.BigInteger(), nullable=True),
    sa.Column('kospi_gap_pct', sa.Float(), nullable=True),
    sa.Column('kosdaq_open', sa.Float(), nullable=True),
    sa.Column('kosdaq_high', sa.Float(), nullable=True),
    sa.Column('kosdaq_low', sa.Float(), nullable=True),
    sa.Column('kosdaq_close', sa.Float(), nullable=True),
    sa.Column('kosdaq_volume', sa.BigInteger(), nullable=True),
    sa.Column('kosdaq_gap_pct', sa.Float(), nullable=True),
    sa.Column('kospi200_open', sa.Float(), nullable=True),
    sa.Column('kospi200_high', sa.Float(), nullable=True),
    sa.Column('kospi200_low', sa.Float(), nullable=True),
    sa.Column('kospi200_close', sa.Float(), nullable=True),
    sa.Column('kospi200_volume', sa.BigInteger(), nullable=True),
    sa.Column('kospi200_gap_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index('idx_market_indices_date', 'market_indices', ['date'], unique=False)
    op.create_table('stock_metadata',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.Enum('KOSPI', 'KOSDAQ', name='exchange'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELISTED', 'SUSPENDED', 'WARNING', name='stockstatus'), nullable=False),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('uid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('MASTER', 'USER', name='userrole'), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('stock_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.BigInteger(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('app_key', sa.String(length=100), nullable=False),
    sa.Column('app_secret', sa.String(length=200), nullable=False),
    sa.Column('kis_access_token', sa.Text(), nullable=True),
    sa.Column('kis_token_expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('gap_pct', sa.Float(), nullable=True),
    sa.Column('prev_return', sa.Float(), nullable=True),
    sa.Column('prev_range_pct', sa.Float(), nullable=True),
    sa.Column('prev_upper_shadow', sa.Float(), nullable=True),
    sa.Column('prev_lower_shadow', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_ratio', sa.Float(), nullable=True),
    sa.Column('bollinger_position', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('ma_5', sa.Float(), nullable=True),
    sa.Column('ma_20', sa.Float(), nullable=True),
    sa.Column('ma_50', sa.Float(), nullable=True),
    sa.Column('above_ma5', sa.Float(), nullable=True),
    sa.Column('above_ma20', sa.Float(), nullable=True),
    sa.Column('above_ma50', sa.Float(), nullable=True),
    sa.Column('ma5_ma20_cross', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_20d', sa.Float(), nullable=True),
    sa.Column('consecutive_up_days', sa.Float(), nullable=True),
    sa.Column('market_gap_diff', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_stock_prices_symbol_date')
    )
    op.create_index('idx_stock_prices_date', 'stock_prices', ['date'], unique=False)
    op.create_index('idx_stock_prices_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_prices_symbol_date', table_name='stock_prices')
    op.drop_index('idx_stock_prices_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('stock_accounts')
    op.drop_table('users')
    op.drop_table('stock_metadata')
    op.drop_index('idx_market_indices_date', table_name='market_indices')
    op.drop_table('market_indices')
    # ### end Alembic commands ###
