"""add model_registry table

Revision ID: 401f90642e4f
Revises: 299c0143e752
Create Date: 2026-01-30 16:37:08.891111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '401f90642e4f'
down_revision: Union[str, Sequence[str], None] = '299c0143e752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('training_data_start', sa.String(length=10), nullable=True),
    sa.Column('training_data_end', sa.String(length=10), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('training_duration_seconds', sa.Float(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'ACTIVE', 'RETIRED', 'REJECTED', name='modelstatus'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_registry')
    # ### end Alembic commands ###
