"""init

Revision ID: 4664a9c3361c
Revises: 
Create Date: 2026-01-19 10:00:57.675717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4664a9c3361c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kospi_open', sa.Float(), nullable=True),
    sa.Column('kospi_high', sa.Float(), nullable=True),
    sa.Column('kospi_low', sa.Float(), nullable=True),
    sa.Column('kospi_close', sa.Float(), nullable=True),
    sa.Column('kospi_volume', sa.BigInteger(), nullable=True),
    sa.Column('kospi_gap_pct', sa.Float(), nullable=True),
    sa.Column('kosdaq_open', sa.Float(), nullable=True),
    sa.Column('kosdaq_high', sa.Float(), nullable=True),
    sa.Column('kosdaq_low', sa.Float(), nullable=True),
    sa.Column('kosdaq_close', sa.Float(), nullable=True),
    sa.Column('kosdaq_volume', sa.BigInteger(), nullable=True),
    sa.Column('kosdaq_gap_pct', sa.Float(), nullable=True),
    sa.Column('kospi200_open', sa.Float(), nullable=True),
    sa.Column('kospi200_high', sa.Float(), nullable=True),
    sa.Column('kospi200_low', sa.Float(), nullable=True),
    sa.Column('kospi200_close', sa.Float(), nullable=True),
    sa.Column('kospi200_volume', sa.BigInteger(), nullable=True),
    sa.Column('kospi200_gap_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index('idx_market_indices_date', 'market_indices', ['date'], unique=False)
    op.create_table('stock_metadata',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.Enum('KOSPI', 'KOSDAQ', name='exchange'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELISTED', 'SUSPENDED', 'WARNING', name='stockstatus'), nullable=False),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('strategy_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_weight',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('weight_type', sa.Enum('EQUAL', 'MARKETCAP', 'VOLUME', 'PRICE', name='weighttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('MASTER', 'USER', 'MOCK', name='userrole'), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.Enum('KOSPI', 'KOSDAQ', name='exchange'), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=True),
    sa.Column('gap_rate', sa.Float(), nullable=False),
    sa.Column('stock_open', sa.Float(), nullable=False),
    sa.Column('prob_up', sa.Float(), nullable=False),
    sa.Column('prob_down', sa.Float(), nullable=False),
    sa.Column('predicted_direction', sa.Integer(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('return_if_up', sa.Float(), nullable=False),
    sa.Column('return_if_down', sa.Float(), nullable=False),
    sa.Column('max_return_if_up', sa.Float(), nullable=True),
    sa.Column('take_profit_target', sa.Float(), nullable=True),
    sa.Column('signal', sa.Enum('BUY', 'HOLD', 'SELL', name='signaltype'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=True),
    sa.Column('actual_close', sa.Float(), nullable=True),
    sa.Column('actual_high', sa.Float(), nullable=True),
    sa.Column('actual_low', sa.Float(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('return_diff', sa.Float(), nullable=True),
    sa.Column('actual_max_return', sa.Float(), nullable=True),
    sa.Column('max_return_diff', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_info.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'prediction_date', name='uq_gap_predictions_stock_date')
    )
    op.create_index('idx_gap_predictions_date', 'predictions', ['prediction_date'], unique=False)
    op.create_index('idx_gap_predictions_signal', 'predictions', ['signal'], unique=False)
    op.create_index('idx_gap_predictions_stock_code', 'predictions', ['stock_code'], unique=False)
    op.create_table('stock_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.BigInteger(), nullable=False),
    sa.Column('hts_id', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('app_key', sa.String(length=100), nullable=False),
    sa.Column('app_secret', sa.String(length=200), nullable=False),
    sa.Column('kis_access_token', sa.Text(), nullable=True),
    sa.Column('kis_token_expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('hts_id')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('gap_pct', sa.Float(), nullable=True),
    sa.Column('prev_return', sa.Float(), nullable=True),
    sa.Column('prev_range_pct', sa.Float(), nullable=True),
    sa.Column('prev_upper_shadow', sa.Float(), nullable=True),
    sa.Column('prev_lower_shadow', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_ratio', sa.Float(), nullable=True),
    sa.Column('bollinger_position', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('ma_5', sa.Float(), nullable=True),
    sa.Column('ma_20', sa.Float(), nullable=True),
    sa.Column('ma_50', sa.Float(), nullable=True),
    sa.Column('above_ma5', sa.Float(), nullable=True),
    sa.Column('above_ma20', sa.Float(), nullable=True),
    sa.Column('above_ma50', sa.Float(), nullable=True),
    sa.Column('ma5_ma20_cross', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_20d', sa.Float(), nullable=True),
    sa.Column('consecutive_up_days', sa.Float(), nullable=True),
    sa.Column('market_gap_diff', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock_metadata.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_stock_prices_symbol_date')
    )
    op.create_index('idx_stock_prices_date', 'stock_prices', ['date'], unique=False)
    op.create_index('idx_stock_prices_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    op.create_table('user_strategy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('investment_weight', sa.Float(), nullable=True),
    sa.Column('ls_ratio', sa.Float(), nullable=False),
    sa.Column('tp_ratio', sa.Float(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=True),
    sa.Column('weight_type_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PAUSED', name='strategystatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['weight_type_id'], ['strategy_weight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_strategy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('buy_amount', sa.Float(), nullable=True),
    sa.Column('sell_amount', sa.Float(), nullable=True),
    sa.Column('total_profit_rate', sa.Float(), nullable=True),
    sa.Column('total_profit_amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_strategy_id'], ['user_strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_strategy_stock',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('daily_strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('stock_open', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('target_quantity', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('buy_quantity', sa.Float(), nullable=True),
    sa.Column('sell_quantity', sa.Float(), nullable=True),
    sa.Column('profit_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_strategy_id'], ['daily_strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('daily_strategy_stock_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.Enum('BUY', 'SELL', name='ordertype'), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=False),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.Column('order_dvsn', sa.String(length=10), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'PARTIALLY_EXECUTED', 'EXECUTED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('total_executed_quantity', sa.Integer(), nullable=False),
    sa.Column('total_executed_price', sa.Float(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('is_fully_executed', sa.Boolean(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_strategy_stock_id'], ['daily_strategy_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_no'), 'order', ['order_no'], unique=True)
    op.create_table('order_execution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('execution_sequence', sa.Integer(), nullable=False),
    sa.Column('executed_quantity', sa.Integer(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=False),
    sa.Column('total_executed_quantity_after', sa.Integer(), nullable=False),
    sa.Column('total_executed_price_after', sa.Float(), nullable=False),
    sa.Column('remaining_quantity_after', sa.Integer(), nullable=False),
    sa.Column('is_fully_executed_after', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_execution_order_id'), 'order_execution', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_execution_order_id'), table_name='order_execution')
    op.drop_table('order_execution')
    op.drop_index(op.f('ix_order_order_no'), table_name='order')
    op.drop_table('order')
    op.drop_table('daily_strategy_stock')
    op.drop_table('daily_strategy')
    op.drop_table('user_strategy')
    op.drop_index('idx_stock_prices_symbol_date', table_name='stock_prices')
    op.drop_index('idx_stock_prices_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('stock_accounts')
    op.drop_index('idx_gap_predictions_stock_code', table_name='predictions')
    op.drop_index('idx_gap_predictions_signal', table_name='predictions')
    op.drop_index('idx_gap_predictions_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('users')
    op.drop_table('strategy_weight')
    op.drop_table('strategy_info')
    op.drop_table('stock_metadata')
    op.drop_index('idx_market_indices_date', table_name='market_indices')
    op.drop_table('market_indices')
    # ### end Alembic commands ###
