"""update market_gap

Revision ID: 4a00e4346074
Revises: 28a5368de9dc
Create Date: 2026-01-12 14:17:12.706261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a00e4346074'
down_revision: Union[str, Sequence[str], None] = '28a5368de9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('market_gap_diff', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_prices', 'market_gap_diff')
    # ### end Alembic commands ###
