"""add user account is_del

Revision ID: 532e0081e248
Revises: bbcc7b4afb5c
Create Date: 2026-01-22 15:11:29.013157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532e0081e248'
down_revision: Union[str, Sequence[str], None] = 'bbcc7b4afb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('stock_accounts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # Step 2: Set default value for existing rows
    op.execute("UPDATE stock_accounts SET is_deleted = FALSE WHERE is_deleted IS NULL")
    # Step 3: Add NOT NULL constraint
    op.alter_column('stock_accounts', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_accounts', 'is_deleted')
    # ### end Alembic commands ###
