"""fix strategy table5

Revision ID: 688f004ca1b3
Revises: 523f8f56492e
Create Date: 2026-01-15 18:18:14.015862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688f004ca1b3'
down_revision: Union[str, Sequence[str], None] = '523f8f56492e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_strategy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('buy_amount', sa.Float(), nullable=True),
    sa.Column('sell_amount', sa.Float(), nullable=True),
    sa.Column('total_profit_rate', sa.Float(), nullable=True),
    sa.Column('total_profit_amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_strategy_id'], ['user_strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_strategy_stock',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('daily_strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('stock_open', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('buy_quantity', sa.Float(), nullable=True),
    sa.Column('sell_quantity', sa.Float(), nullable=True),
    sa.Column('profit_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_strategy_id'], ['daily_strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('user_strategy_strategy_id_fkey'), 'user_strategy', type_='foreignkey')
    op.drop_column('user_strategy', 'strategy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_strategy', sa.Column('strategy_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_strategy_strategy_id_fkey'), 'user_strategy', 'strategy_info', ['strategy_id'], ['id'])
    op.drop_table('daily_strategy_stock')
    op.drop_table('daily_strategy')
    # ### end Alembic commands ###
