"""fix fk strategy id

Revision ID: 850ccf465b16
Revises: 532e0081e248
Create Date: 2026-01-23 18:00:52.643352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850ccf465b16'
down_revision: Union[str, Sequence[str], None] = '532e0081e248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('predictions_strategy_id_fkey'), 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'strategy_info', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key(op.f('predictions_strategy_id_fkey'), 'predictions', 'strategy_info', ['strategy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
