"""fix strategy table

Revision ID: 96837d2fdf78
Revises: 5f84e1dacd10
Create Date: 2026-01-15 11:52:52.149411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96837d2fdf78'
down_revision: Union[str, Sequence[str], None] = '5f84e1dacd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_strategy', sa.Column('ls_ratio', sa.Float(), nullable=False))
    op.add_column('user_strategy', sa.Column('tp_ratio', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategy', 'tp_ratio')
    op.drop_column('user_strategy', 'ls_ratio')
    # ### end Alembic commands ###
