"""add account name and type

Revision ID: 97a1cac327e0
Revises: 2c4c6175cd87
Create Date: 2026-01-21 18:17:25.714879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a1cac327e0'
down_revision: Union[str, Sequence[str], None] = '2c4c6175cd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. ENUM 타입 생성 (PostgreSQL에서 ENUM 타입을 먼저 생성해야 함)
    accounttype_enum = sa.Enum('real', 'paper', 'mock', name='accounttype')
    accounttype_enum.create(op.get_bind(), checkfirst=True)
    
    # 2. account_name 컬럼 추가 (NULL 허용)
    op.add_column('stock_accounts', sa.Column('account_name', sa.String(length=50), nullable=True))
    
    # 3. account_type 컬럼 추가 (NULL 허용, ENUM 타입 사용)
    op.add_column('stock_accounts', sa.Column('account_type', accounttype_enum, nullable=True))
    
    # 4. 기존 데이터에 기본값 설정
    op.execute("UPDATE stock_accounts SET account_name = 'test' WHERE account_name IS NULL")
    op.execute("UPDATE stock_accounts SET account_type = 'real' WHERE account_type IS NULL")
    
    # 5. NOT NULL 제약조건 추가
    op.alter_column('stock_accounts', 'account_name',
                    existing_type=sa.String(length=50),
                    nullable=False)
    op.alter_column('stock_accounts', 'account_type',
                    existing_type=accounttype_enum,
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_accounts', 'account_type')
    op.drop_column('stock_accounts', 'account_name')
    
    # ENUM 타입 삭제
    sa.Enum(name='accounttype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
