"""add account name and type

Revision ID: 97a1cac327e0
Revises: 2c4c6175cd87
Create Date: 2026-01-21 18:17:25.714879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a1cac327e0'
down_revision: Union[str, Sequence[str], None] = '2c4c6175cd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_accounts', sa.Column('account_name', sa.String(length=50), nullable=True))
    op.add_column('stock_accounts', sa.Column('account_type', sa.Enum('REAL', 'PAPER', 'MOCK', name='accounttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_accounts', 'account_type')
    op.drop_column('stock_accounts', 'account_name')
    # ### end Alembic commands ###
