"""add minutes candle

Revision ID: 9b88644afe68
Revises: 850ccf465b16
Create Date: 2026-01-26 13:41:29.993558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b88644afe68'
down_revision: Union[str, Sequence[str], None] = '850ccf465b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minute_candle_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('candle_date', sa.Date(), nullable=False),
    sa.Column('candle_time', sa.Time(), nullable=False),
    sa.Column('minute_interval', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'candle_date', 'candle_time', 'minute_interval', name='uq_minute_candle_stock_date_time_interval')
    )
    op.create_index('idx_minute_candle_date', 'minute_candle_data', ['candle_date'], unique=False)
    op.create_index('idx_minute_candle_interval', 'minute_candle_data', ['minute_interval'], unique=False)
    op.create_index('idx_minute_candle_stock_code', 'minute_candle_data', ['stock_code'], unique=False)
    op.create_index('idx_minute_candle_stock_date', 'minute_candle_data', ['stock_code', 'candle_date'], unique=False)
    op.create_index('idx_minute_candle_stock_date_interval', 'minute_candle_data', ['stock_code', 'candle_date', 'minute_interval'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_minute_candle_stock_date_interval', table_name='minute_candle_data')
    op.drop_index('idx_minute_candle_stock_date', table_name='minute_candle_data')
    op.drop_index('idx_minute_candle_stock_code', table_name='minute_candle_data')
    op.drop_index('idx_minute_candle_interval', table_name='minute_candle_data')
    op.drop_index('idx_minute_candle_date', table_name='minute_candle_data')
    op.drop_table('minute_candle_data')
    # ### end Alembic commands ###
