"""fix strategy_table_add_order_table

Revision ID: b783be5e546d
Revises: 01706b4ad2b4
Create Date: 2026-01-18 14:31:01.125471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b783be5e546d'
down_revision: Union[str, Sequence[str], None] = '01706b4ad2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('daily_strategy_stock_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.Enum('BUY', 'SELL', name='ordertype'), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=False),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.Column('order_dvsn', sa.String(length=10), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'PARTIALLY_EXECUTED', 'EXECUTED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('total_executed_quantity', sa.Integer(), nullable=False),
    sa.Column('total_executed_price', sa.Float(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('is_fully_executed', sa.Boolean(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_strategy_stock_id'], ['daily_strategy_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_no'), 'order', ['order_no'], unique=True)
    op.create_table('order_execution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('execution_sequence', sa.Integer(), nullable=False),
    sa.Column('executed_quantity', sa.Integer(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=False),
    sa.Column('total_executed_quantity_after', sa.Integer(), nullable=False),
    sa.Column('total_executed_price_after', sa.Float(), nullable=False),
    sa.Column('remaining_quantity_after', sa.Integer(), nullable=False),
    sa.Column('is_fully_executed_after', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_execution_order_id'), 'order_execution', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_execution_order_id'), table_name='order_execution')
    op.drop_table('order_execution')
    op.drop_index(op.f('ix_order_order_no'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
