"""fix strategy table3

Revision ID: b9a4a70bf1c8
Revises: 96837d2fdf78
Create Date: 2026-01-15 13:21:32.200075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a4a70bf1c8'
down_revision: Union[str, Sequence[str], None] = '96837d2fdf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # enum 타입 먼저 생성
    strategystatus = sa.Enum('ACTIVE', 'INACTIVE', 'PAUSED', name='strategystatus')
    strategystatus.create(op.get_bind(), checkfirst=True)

    op.add_column('user_strategy', sa.Column('is_auto', sa.Boolean(), nullable=True))
    op.add_column('user_strategy', sa.Column('status', strategystatus, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategy', 'status')
    op.drop_column('user_strategy', 'is_auto')

    # enum 타입 삭제
    sa.Enum(name='strategystatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
