"""change user_strategy fk from user_id to account_id

Revision ID: bbcc7b4afb5c
Revises: dd09e9e337f8
Create Date: 2026-01-21 22:53:13.040383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcc7b4afb5c'
down_revision: Union[str, Sequence[str], None] = 'dd09e9e337f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. account_id 컬럼 추가 (nullable=True로 먼저)
    op.add_column('user_strategy', sa.Column('account_id', sa.BigInteger(), nullable=True))

    # 2. 기존 user_id를 account_id로 매핑 (user의 첫 번째 계좌로)
    op.execute("""
        UPDATE user_strategy us
        SET account_id = (
            SELECT sa.id FROM stock_accounts sa
            WHERE sa.user_uid = us.user_id
            ORDER BY sa.id
            LIMIT 1
        )
    """)

    # 3. account_id가 NULL인 행 삭제 (매핑 실패한 경우)
    op.execute("DELETE FROM user_strategy WHERE account_id IS NULL")

    # 4. account_id를 NOT NULL로 변경
    op.alter_column('user_strategy', 'account_id', nullable=False)

    # 5. FK 변경
    op.drop_constraint(op.f('user_strategy_user_id_fkey'), 'user_strategy', type_='foreignkey')
    op.create_foreign_key(None, 'user_strategy', 'stock_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_strategy', 'user_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_strategy', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_strategy', type_='foreignkey')
    op.create_foreign_key(op.f('user_strategy_user_id_fkey'), 'user_strategy', 'users', ['user_id'], ['uid'])
    op.drop_column('user_strategy', 'account_id')
    # ### end Alembic commands ###
