"""fix usertable hts_id

Revision ID: c2e402d38147
Revises: 8780debdacfd
Create Date: 2026-01-16 14:46:04.184514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e402d38147'
down_revision: Union[str, Sequence[str], None] = '8780debdacfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_accounts', sa.Column('hts_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'stock_accounts', ['hts_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_accounts', type_='unique')
    op.drop_column('stock_accounts', 'hts_id')
    # ### end Alembic commands ###
