"""add candle table

Revision ID: c661ec196c07
Revises: 4664a9c3361c
Create Date: 2026-01-21 00:39:50.752440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c661ec196c07'
down_revision: Union[str, Sequence[str], None] = '4664a9c3361c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hour_candle_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('candle_date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'candle_date', 'hour', name='uq_hour_candle_stock_date_hour')
    )
    op.create_index('idx_hour_candle_date', 'hour_candle_data', ['candle_date'], unique=False)
    op.create_index('idx_hour_candle_stock_code', 'hour_candle_data', ['stock_code'], unique=False)
    op.create_index('idx_hour_candle_stock_date', 'hour_candle_data', ['stock_code', 'candle_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hour_candle_stock_date', table_name='hour_candle_data')
    op.drop_index('idx_hour_candle_stock_code', table_name='hour_candle_data')
    op.drop_index('idx_hour_candle_date', table_name='hour_candle_data')
    op.drop_table('hour_candle_data')
    # ### end Alembic commands ###
