"""fix strategy_table_add_weight2

Revision ID: d599c7d66b9b
Revises: 22486c0131ef
Create Date: 2026-01-16 18:32:25.321280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd599c7d66b9b'
down_revision: Union[str, Sequence[str], None] = '22486c0131ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategy', 'weight_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_strategy', sa.Column('weight_type', postgresql.ENUM('EQUAL', 'MARKETCAP', 'VOLUME', 'PRICE', name='weighttype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
