"""add user strategy is_del

Revision ID: dd09e9e337f8
Revises: 97a1cac327e0
Create Date: 2026-01-21 21:54:04.355919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd09e9e337f8'
down_revision: Union[str, Sequence[str], None] = '97a1cac327e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_accounts', 'account_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('stock_accounts', 'account_type',
               existing_type=postgresql.ENUM('REAL', 'PAPER', 'MOCK', name='accounttype'),
               nullable=False)
    op.add_column('user_strategy', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategy', 'is_deleted')
    op.alter_column('stock_accounts', 'account_type',
               existing_type=postgresql.ENUM('REAL', 'PAPER', 'MOCK', name='accounttype'),
               nullable=True)
    op.alter_column('stock_accounts', 'account_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
