"""add columns metadata

Revision ID: eb7c0154a99b
Revises: 9b88644afe68
Create Date: 2026-01-29 10:57:31.050913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7c0154a99b'
down_revision: Union[str, Sequence[str], None] = '9b88644afe68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_metadata', sa.Column('is_nxt_tradable', sa.Boolean(), nullable=True))
    op.add_column('stock_metadata', sa.Column('is_nxt_stopped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_metadata', 'is_nxt_stopped')
    op.drop_column('stock_metadata', 'is_nxt_tradable')
    # ### end Alembic commands ###
