"""add_kis_token_to_accounts

Revision ID: ef800be6115b
Revises: 1b58beac5c63
Create Date: 2026-01-11 18:47:26.933880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef800be6115b'
down_revision: Union[str, Sequence[str], None] = '1b58beac5c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_accounts', sa.Column('kis_access_token', sa.Text(), nullable=True))
    op.add_column('stock_accounts', sa.Column('kis_token_expired_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_accounts', 'kis_token_expired_at')
    op.drop_column('stock_accounts', 'kis_access_token')
    # ### end Alembic commands ###
